name: "TakeMeBack"
version: '${version}'
main: "me.byteful.plugin.tmb.TakeMeBackPlugin"
api-version: "1.13"
author: "byteful"
description: "A Spigot/Bukkit plugin that spawns a particle trail from your starting location to help you make your way back there."
commands:
  takemeback:
    description: "Toggle the particle trail on and off."
    permission: "takemeback.use"
    aliases:
      - "tmb"
permissions:
  takemeback.use:
    description: "Permission to use /takemeback"
    default: true